DEFAULT_WIDTH = 512
DEFAULT_HEIGHT = 512


MEME_TEMPLATES_DATABASE = [
    {"id": "aag", "lines": 2, "template": "Ты реально думаешь, что "},
    {"id": "ackbar", "lines": 2, "template": "Это ловушка, "},
    {"id": "afraid", "lines": 2, "template": "Вы хотите сказать мне, что я "},
    {"id": "agnes", "lines": 2, "template": "Я бы хотел сказать, что "},
    {"id": "aint-got-time", "lines": 2, "template": "Нет, только не "},
    {"id": "ams", "lines": 2, "template": ""},
    {"id": "ants", "lines": 2, "template": "Вы точно "},
    {"id": "astronaut", "lines": 4, "template": "Я, который пытается сделать "},
    {"id": "atis", "lines": 2, "template": ""},
    {"id": "away", "lines": 2, "template": "Вы серьёзно, ?"},
    {"id": "bad", "lines": 2, "template": "Фуу "},
    {"id": "balloon", "lines": 3, "template": "Я хочу вот так "},
    {"id": "bd", "lines": 2, "template": "Вообщето "},
    {"id": "because", "lines": 2, "template": "Эй, "},
    {"id": "bender", "lines": 2, "template": "Подержите мое пиво "},
    {"id": "bilbo", "lines": 2, "template": "Моя прелесть, "},
    {"id": "boat", "lines": 2, "template": "Я вас услышал, "},
    {"id": "bongo", "lines": 2, "template": "Парам пам пам "},
    {"id": "box", "lines": 2, "template": "Нет, мои финики "},
    {"id": "bs", "lines": 2, "template": "Подозрительно, но "},
    {"id": "bus", "lines": 2, "template": ""},
    {"id": "buzz", "lines": 2, "template": "Представь, "},
    {"id": "captain-america", "lines": 3, "template": "Вы не правы "},
    {"id": "cbb", "lines": 2, "template": "НАШЕ "},
    {"id": "cbg", "lines": 2, "template": "Ну такое "},
    {"id": "center", "lines": 2, "template": "Просто посмотрите на это "},
    {"id": "ch", "lines": 2, "template": "Вам туда "},
    {"id": "chair", "lines": 6, "template": "Ты не можешь делать так, "},
    {"id": "cheems", "lines": 2, "template": "Aфигенно "},
    {"id": "chosen", "lines": 2, "template": "Ты должен был "},
    {"id": "cmm", "lines": 1, "template": "Ну давай, нападай со своими "},
    {"id": "cryingfloor", "lines": 2, "template": "Грустно из-за того, что "},
    {"id": "db", "lines": 3, "template": "Я, когда "},
    {"id": "dbg", "lines": 2, "template": "Вначале , после "},
    {"id": "disastergirl", "lines": 2, "template": "Вы меня еще плохо знаете "},
    {"id": "dodgson", "lines": 2, "template": "Почему он, а не "},
    {"id": "doge", "lines": 2, "template": "Хих "},
    {"id": "drake", "lines": 2, "template": "Делать вот так , "},
    {"id": "drowning", "lines": 3, "template": "Давай до связи "},
    {"id": "ds", "lines": 3, "template": ", или не "},
    {"id": "dwight", "lines": 2, "template": "Что ты сказал? "},
    {"id": "elmo", "lines": 5, "template": "Ммм, пудрочка "},
    {"id": "exit", "lines": 3, "template": "Успех, "},
    {"id": "facepalm", "lines": 2, "template": "Чел, "},
    {"id": "fbf", "lines": 2, "template": "Невероятно, но "},
    {"id": "feelsgood", "lines": 2, "template": "Боже, "},
    {"id": "fine", "lines": 2, "template": "Всё нормаль, просто "},
    {"id": "firsttry", "lines": 2, "template": "В первый раз "},
    {"id": "fry", "lines": 2, "template": "Я это запомню "},
    {"id": "gandalf", "lines": 2, "template": "Я многое повидал, но вот это "},
    {"id": "gb", "lines": 4, "template": "просто , супер , мега , сверх "},
    {"id": "gears", "lines": 2, "template": "Гребанные "},
    {"id": "genie", "lines": 2, "template": "А можно "},
    {"id": "ggg", "lines": 2, "template": "Туроператор маями "},
    {"id": "glasses", "lines": 2, "template": "Я что, , хотя "},
    {"id": "gone", "lines": 2, "template": "Мальборо блэк "},
    {"id": "grave", "lines": 3, "template": "Мой кент, когда сделал "},
    {
        "id": "gru",
        "lines": 4,
        "template": "Сначала мы , затем внезапно , и вот когда наконце , что за ?",
    },
    {"id": "grumpycat", "lines": 2, "template": "И зачем ты это мне сказал "},
    {"id": "hagrid", "lines": 2, "template": "Емое "},
    {"id": "handshake", "lines": 3, "template": "Дружить , хотеть "},
    {"id": "happening", "lines": 2, "template": "А ди ла ди дай "},
    {"id": "harold", "lines": 2, "template": "Скажите это моему "},
    {"id": "imsorry", "lines": 2, "template": "Это были всего навсего "},
    {"id": "interesting", "lines": 2, "template": "Что же вы скажите на "},
    {"id": "iw", "lines": 2, "template": "Волк в цирке не "},
    {
        "id": "jetpack",
        "lines": 2,
        "template": "Что ты мне сделаешь, я в другом городе ",
    },
    {"id": "jim", "lines": 2, "template": "Просто делайте вот так: , и всё "},
    {"id": "joker", "lines": 2, "template": "И  испарился!"},
    {"id": "kermit", "lines": 2, "template": "Ммм, , идиот"},
    {"id": "khaby-lame", "lines": 2, "template": "Вы , а надо просто "},
    {"id": "leo", "lines": 2, "template": "А я иду "},
    {"id": "light", "lines": 2, "template": "Представь, что это "},
    {"id": "ll", "lines": 2, "template": ""},
    {"id": "lrv", "lines": 2, "template": "Когда  выбрал викингов!"},
    {"id": "made", "lines": 5, "template": "На , ты потерял "},
    {"id": "mb", "lines": 2, "template": "Люблю эти фрукты "},
    {"id": "michael-scott", "lines": 2, "template": "Ты не можешь "},
    {"id": "midwit", "lines": 3, "template": "Дурачки , нормиcы , гигачады "},
    {"id": "mini-keanu", "lines": 2, "template": "Растишка для "},
    {"id": "money", "lines": 2, "template": "Заткнись и дай мне "},
    {"id": "mordor", "lines": 2, "template": " просто отвратителен"},
    {"id": "morpheus", "lines": 2, "template": "Что такое , Нео?"},
    {"id": "mouth", "lines": 3, "template": "Закрой свой "},
    {"id": "nails", "lines": 3, "template": "Пасейдон, уходи от "},
    {
        "id": "noah",
        "lines": 4,
        "template": "Ну и что вы сделали: я просил , а вы что ",
    },
    {"id": "noidea", "lines": 2, "template": "Я у мамы "},
    {"id": "oag", "lines": 2, "template": "Привет, давай "},
    {"id": "officespace", "lines": 2, "template": "Подтяжки, да, кстати "},
    {"id": "older", "lines": 2, "template": "Я: "},
    {"id": "oprah", "lines": 2, "template": ""},
    {
        "id": "panik-kalm-panik",
        "lines": 3,
        "template": "У нас проблема , Есть решение , Но теперь у нас снова ",
    },
    {"id": "patrick", "lines": 2, "template": "Ало, это , нет это "},
    {
        "id": "perfection",
        "lines": 6,
        "template": ". Покажи мне , я сказал . Настоящий . Нет еще более лучший . Идеальный . Прекрасно.",
    },
    {
        "id": "philosoraptor",
        "lines": 2,
        "template": "А вы знали, что если , то будет ",
    },
    {"id": "pigeon", "lines": 3, "template": ", также "},
    {"id": "pooh", "lines": 2, "template": "Когда сказал не , а сказал "},
    {"id": "pool", "lines": 3, "template": "Мое , когда , "},
    {"id": "remembers", "lines": 2, "template": "А вот в наше "},
    {
        "id": "reveal",
        "lines": 4,
        "template": "Посмотрим, кто под , , Смотрите это , под маской был ",
    },
    {"id": "right", "lines": 5, "template": "Ты правда считаешь , Я думаю , , "},
    {"id": "rollsafe", "lines": 1, "template": "Подумай еще раз об "},
    {"id": "sad-biden", "lines": 2, "template": "Когда ты , а она "},
    {"id": "sad-obama", "lines": 2, "template": "Подъезды , больше не "},
    {"id": "sadfrog", "lines": 2, "template": "Были же , а теперь "},
    {"id": "saltbae", "lines": 2, "template": "Насыпал тут "},
    {"id": "say", "lines": 2, "template": "Посмотрите на , он такой !"},
    {"id": "sb", "lines": 2, "template": "Держи, "},
    {
        "id": "seagull",
        "lines": 2,
        "template": "Сколько уже можно , дайте наконец то мне ",
    },
    {"id": "sk", "lines": 2, "template": " - белая темка, отвечаю"},
    {
        "id": "ski",
        "lines": 2,
        "template": "Это оказалось сложнее, чем , хотя я думал ",
    },
    {"id": "slap", "lines": 2, "template": "Будь здоров, "},
    {"id": "soa", "lines": 2, "template": "Чиназес, "},
    {"id": "sohappy", "lines": 2, "template": "Спасибо, что ты , а не "},
    {"id": "sparta", "lines": 2, "template": "Нет, это !"},
    {"id": "spiderman", "lines": 2, "template": "Я говорю , а он говорит "},
    {"id": "spongebob", "lines": 2, "template": "Наш корабль идет ко дну "},
    {"id": "stonks", "lines": 2, "template": "Вкладываемся в , на выходе получаем "},
    {"id": "success", "lines": 2, "template": "Перезвони "},
    {"id": "toohigh", "lines": 2, "template": "Черным по белому объясняю "},
    {"id": "touch", "lines": 2, "template": "Хм, . А вспомнил, что "},
    {"id": "trump", "lines": 2, "template": "Сделай свои слова снова великими "},
    {"id": "ugandanknuck", "lines": 2, "template": "-"},
    {"id": "vince", "lines": 3, "template": "Прекрасный , Вкатывающий , "},
    {"id": "waygd", "lines": 2, "template": "Не волнуйся , бывает"},
    {"id": "wddth", "lines": 2, "template": "Ну, ты , города не путай"},
    {"id": "wkh", "lines": 3, "template": ". А теперь вернемся к "},
    {"id": "woman-cat", "lines": 2, "template": "Да ты не можешь . А я "},
    {"id": "wonka", "lines": 2, "template": "В школе расскажишь об "},
    {"id": "xy", "lines": 2, "template": "Завтра "},
    {"id": "yuno", "lines": 2, "template": "Да хватит уже говорить об . Вы меня "},
]
